basePath: /
definitions:
  http.HealthResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  description: API documentation for Feedback Hub.
  title: Feedback Hub API
  version: "1.0"
paths:
  /healthz:
    get:
      description: Returns health status
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.HealthResponse'
      summary: Health check
      tags:
      - health
swagger: "2.0"
